apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: task-api
spec:
  replicas: 3

  strategy:
    canary:
      analysis:
        templates:
        - templateName: success-rate-check

      steps:
      - setWeight: 20
      - pause: {duration: 60}

      - setWeight: 50
      - pause: {duration: 60}

      - setWeight: 100

  selector:
    matchLabels:
      app: task-api

  template:
    metadata:
      labels:
        app: task-api

    spec:
      containers:
      - name: task-api
        image: docker.io/abhigyanmohanta/task-api:16
        ports:
        - containerPort: 5000
