apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: task-api-scaler
spec:
  scaleTargetRef:
    name: task-api

  minReplicaCount: 1
  maxReplicaCount: 10

  cooldownPeriod: 30
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
      metricName: http_requests_rate
      threshold: '10'
      query: sum(rate(http_requests_total{service="task-api"}[1m]))
